// Independent verifier for bounded calibration-loader observer evidence.
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.HexFormat
import java.util.zip.ZipFile

require(args.size in 1..2){"Usage: VerifyCalibrationLoaders.main.kts RUN_DIRECTORY [76..89]"}
val run=Path.of(args[0]).toAbsolutePath().normalize()
fun bytes(name:String)=Files.readAllBytes(run.resolve(name));fun text(name:String)=Files.readString(run.resolve(name))
fun hash(b:ByteArray)=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));fun hash(name:String)=hash(bytes(name))
data class E(val kind:String,val f:Map<String,String>){fun s(k:String)=f.getValue(k);fun u(k:String)=s(k).removePrefix("0x").toULong(16)}
fun events(name:String)=text(name).split("[[events]]").drop(1).map{block->val pairs=block.lineSequence().filter{it.isNotBlank()}.map{line->val p=line.split(" = ",limit=2);require(p.size==2){"bad event line"};p[0] to p[1].removeSurrounding("\"")}.toList();require(pairs.map{it.first}.distinct().size==pairs.size);val f=pairs.toMap();E(f.getValue("kind"),f)}
data class R(val tid:ULong,val pc:ULong,val relative:ULong,val sp:ULong,val pstate:ULong,val x:List<ULong>)
fun regs(e:E)=R(e.u("tid"),e.u("pc"),e.u("relative_pc"),e.u("sp"),e.u("pstate"),(0..30).map{e.u("x"+it.toString().padStart(2,'0'))})
fun same(a:R,b:R)=a.tid==b.tid&&a.pc==b.pc&&a.sp==b.sp&&a.pstate==b.pstate&&a.x==b.x
fun completed(before:R,after:R,readValue:ULong?):Boolean { if(before.tid!=after.tid||after.pc!=before.pc+4uL||after.sp!=before.sp||after.pstate!=before.pstate)return false;return (0..30).all{i->after.x[i]==if(i==9&&readValue!=null)readValue else before.x[i]} }
data class Seg(val off:ULong,val va:ULong,val size:ULong,val flags:ULong)
class Elf(val b:ByteArray){fun u16(i:Int)=ByteBuffer.wrap(b,i,2).order(ByteOrder.LITTLE_ENDIAN).short.toUShort().toInt();fun u32(i:Int)=ByteBuffer.wrap(b,i,4).order(ByteOrder.LITTLE_ENDIAN).int.toUInt().toULong();fun u64(i:Int)=ByteBuffer.wrap(b,i,8).order(ByteOrder.LITTLE_ENDIAN).long.toULong();val segs:List<Seg>
 init{require(b.take(6)==listOf(127,69,76,70,2,1).map{it.toByte()}&&u16(18)==183);segs=(0 until u16(56)).map{u64(32).toInt()+it*u16(54)}.filter{u32(it)==1uL}.map{Seg(u64(it+8),u64(it+16),u64(it+32),u32(it+4))}}
 fun word(va:ULong):ULong{val s=segs.single{va>=it.va&&va+4uL<=it.va+it.size};return u32((s.off+va-s.va).toInt())}
 fun symbol(name:String):ULong{val hs=(0 until u16(60)).map{u64(40).toInt()+it*u16(58)};val tab=hs.single{u32(it+4)==2uL};val strings=hs[u32(tab+40).toInt()];val matches=(0 until(u64(tab+32)/u64(tab+56)).toInt()).map{i->val p=u64(tab+24).toInt()+i*u64(tab+56).toInt();val a=u64(strings+24).toInt()+u32(p).toInt();var z=a;while(b[z]!=0.toByte())z++;String(b,a,z-a) to u64(p+8)}.filter{it.first==name};return matches.single().second}}

// Protocol-specific verification follows.
val candidateHash="6f84cda746319f02b701065bdbfe27b8e051d26b5b6a2eacba8309f85ae3dcb3"
val controlsHash="a135578c6f14acdd8423cd16359667572c8260b03c0fcc5482adf0b3cec933f9"
require(hash("calibration-loader-candidate.toml")==candidateHash&&hash("calibration-loader-controls.toml")==controlsHash){"loader contract pins"}
data class A(val arm:Int,val outcome:String,val reason:String?)
val arms=text("calibration-loader-controls.toml").split("[[arms]]").drop(1).map { block ->
 fun field(name:String)=Regex("(?m)^"+name+" = \"?([^\\n\"]+)\"?$").find(block)?.groupValues?.get(1)
 A(field("arm")!!.toInt(),field("outcome")!!,field("reason"))
};require(arms.map{it.arm}==(76..89).toList())
val nativeHash="3c045ce88aeebf61da55e6026216995bbf562bf5ddd12560b9e4ce4296df40fa"
fun pattern(n:Int,mul:Int,add:Int)=ByteArray(n){i->(i*mul+add).toByte()}
fun checkFile(name:String,expected:ByteArray){val actual=bytes(name);require(actual.size==expected.size&&actual.contentEquals(expected)){"capture $name"}}
fun dump(e:E,address:ULong,control:ULong,request:Boolean){require(e.u("result")==0uL&&e.u("size")== (if(request)24uL else 264uL) &&e.u("info")==0x606uL&&e.u("a00")==address&&e.u("c00")==control);for(i in 1..15){val n=i.toString().padStart(2,'0');require(e.u("a$n")==0uL&&e.u("c$n")==0uL)}}
fun verify(a:A){
 val arm=a.arm;val prefix="loader-$arm";require(text("$prefix-status.toml").trim()=="exit_code = 78")
 val binary=bytes("group-control.elf");require(hash("$prefix.elf")==hash(binary)&&hash(binary)==text("binary-sha256.txt").take(64));require(hash(binary)==nativeHash)
 val elf=Elf(binary);val es=events("$prefix.toml");require(es.isNotEmpty());val model=es.single{it.kind=="model-mode"};require(model.s("scope")=="private"&&model.u("arm")==arm.toULong()&&model.u("remaining")==1uL&&model.u("tail")==1uL)
 val mb=es.single{it.kind=="model-binding"};val pid=mb.u("pid");val shared=mb.u("object")-48uL;require(shared and 4095uL==0uL);val observer=es.single{it.kind=="ready"}.u("observer_pid")
 val lm=es.single{it.kind=="loader-mode"};require(lm.s("scope")=="private"&&lm.u("arm")==arm.toULong()&&lm.u("profile")==2uL&&lm.s("debug_profile")=="inherited-direct-arm-v1"&&lm.u("checkpoint_count")==4uL&&lm.u("capture_count")==5uL&&lm.u("binding_count")==6uL&&lm.u("deadline_ms")==10000uL)
 // Exact inherited transport prefix: two reads, 464 writes, ten remaining checkpoints, three tail checkpoints.
 val modeledReads=es.filter{it.kind=="modeled-read"};require(modeledReads.map{it.u("index") to it.u("value")}==listOf(0uL to 0xe1234567uL,1uL to 0x89abcdefuL))
 val writes=es.filter{it.kind=="modeled-write"};require(writes.size==466&&writes.map{it.u("index")}==(0..465).map{it.toULong()}&&writes.all{it.u("tid")==pid&&it.u("width")==4uL})
 val oracle=Files.readAllLines(run.resolve("reference.tsv")).drop(1).mapIndexed{i,line->val f=line.split('\t');require(f.size==7&&f[0].toInt()==i);f[6].removePrefix("0x").toULong(16)};val spu=ByteBuffer.wrap(bytes("spu-private.bin")).order(ByteOrder.LITTLE_ENDIAN);val su32:(Int)->ULong={i->spu.getInt(i).toUInt().toULong()};val offsets=List(452){0x3000uL}+(0..7).map{su32(1000+8*it)}+listOf(0x4004uL,0x4004uL,0x7034uL,0x7034uL);val values=oracle+(0..7).map{su32(1004+8*it)}+listOf(0x80000000uL,0uL,1uL,0uL);writes.take(464).forEachIndexed{i,e->require(e.u("offset")==offsets[i]&&e.u("value")==values[i])}
 val oldCp=es.filter{it.kind=="remaining-checkpoint"};val oldGuards=es.filter{it.kind=="remaining-checkpoint-guard"};require(oldCp.map{it.u("index")}==(0..9).map{it.toULong()}&&oldGuards.size==10&&oldGuards.all{it.u("match")==1uL});val tailCp=es.filter{it.kind=="tail-checkpoint"};val tailGuards=es.filter{it.kind=="tail-checkpoint-guard"};require(tailCp.map{it.u("index")}==(0..2).map{it.toULong()}&&tailGuards.size==3&&tailGuards.all{it.u("match")==1uL});require(es.single{it.kind=="tail-summary"}.let{it.u("reads")==10uL&&it.u("writes")==2uL&&it.u("checkpoints")==3uL&&it.u("total_writes")==466uL})
 val mapping=es.single{it.kind=="mapping-result"}.u("base");val readPc=elf.symbol("gm_first_pc");val writePc=elf.symbol("gm_write_pc");val ro=listOf(4uL,0uL,0x401cuL,0x14a0uL,0x14a4uL,0x1498uL,0x14acuL,0x14b4uL,0x1008uL,0x1210uL);val rv=listOf(0xa1123456uL,0xbbaa0078uL,0x10203040uL,0xa5a50021uL,0xb6b61234uL,0xc7c72345uL,0xd8d83456uL,0xe9e94567uL,0x20000000uL,62500uL);val tw=es.filter{it.kind=="tail-write"};val tr=es.filter{it.kind=="tail-read"};require(tr.size==10&&tw.size==2&&es.count{it.kind=="tail-read-registers"}==10)
 tr.forEachIndexed{i,e->require(e.u("index")==i.toULong()&&e.u("tid")==pid&&e.u("offset")==ro[i]&&e.u("value")==rv[i]&&e.u("width")==4uL&&e.u("pc")==readPc&&e.u("opcode")==0xb9400109uL);val q=es.indexOf(e);val f=es.subList(0,q).last{it.kind=="mapped-fault"};val br=regs(es.subList(0,q).last{it.kind=="fault-registers"});require(f.u("address")==mapping+ro[i]&&f.u("signal")==11uL&&f.u("si_code")==2uL&&br.x[8]==f.u("address")&&completed(br,regs(es[q+1]),rv[i]))}
 val wo=listOf(0x1428uL,0x1000uL);val wv=listOf(0x646euL,0uL);tw.forEachIndexed{i,e->require(e.u("index")==i.toULong()&&e.u("global_index")==464uL+i.toULong()&&e.u("offset")==wo[i]&&e.u("value")==wv[i]&&e.u("pc")==writePc&&e.u("opcode")==0xb9000109uL);val q=es.indexOf(e);val f=es.subList(0,q).last{it.kind=="mapped-fault"};val br=regs(es.subList(0,q).last{it.kind=="fault-registers"});require(f.u("address")==mapping+wo[i]&&br.x[8]==f.u("address")&&br.x[9].toUInt().toULong()==wv[i]&&completed(br,regs(es[q+1]),null));require(writes[464+i].u("offset")==wo[i]&&writes[464+i].u("value")==wv[i])}
 val tailTokens=es.filter{it.kind in setOf("tail-read","tail-write","tail-checkpoint")}.map{if(it.kind=="tail-read")"R${it.u("index")}" else if(it.kind=="tail-write")"W${it.u("index")}" else "CP${it.u("index")}"};require(tailTokens==listOf("R0","R1","R2","W0","CP0","R3","R4","R5","R6","R7","W1","R8","R9","CP1","CP2"))
 // Bindings and layout are derived from the private ELF/shared layout, not match flags.
 val symbols=listOf("gm_tail_private","gm_loader_private","gm_private_leader","gm_cl_cp0","gm_cl_cp1","gm_cl_cp2").map{elf.symbol(it)};val bindings=es.filter{it.kind=="loader-binding"};val bindingCount=if(arm==81)3 else 6;require(bindings.map{it.u("index")}==(0 until bindingCount).map{it.toULong()});bindings.forEachIndexed{i,e->val actual=symbols[i]+if(arm==81&&i==2)1uL else 0uL;require(e.u("slot")==shared+3224uL+8uL*i.toULong()&&e.u("expected_target")==symbols[i]&&e.u("actual_target")==actual&&e.u("match")==if(actual==symbols[i])1uL else 0uL)}
 val layout=es.filter{it.kind=="loader-layout"};val layoutCount=when(arm){81->0;82,83->6;else->7};require(layout.size==layoutCount)
 val objectAddresses=listOf(shared,shared+3200uL,shared+3216uL,shared+3208uL)
 layout.take(minOf(4,layout.size)).forEachIndexed{i,e->require(e.s("category")=="object"&&e.s("evidence_kind")=="derived-fixed-layout"&&e.u("index")==i.toULong()&&e.u("address")==objectAddresses[i]&&e.u("expected_address")==objectAddresses[i]&&e.u("length")==0uL&&e.u("expected_length")==0uL&&e.u("match")==1uL)}
 val destinations=layout.drop(4);val baseLsb=if(destinations.isEmpty())0uL else destinations[0].u("expected_address");val addresses=listOf(baseLsb,baseLsb+0x1000uL,baseLsb+0x3000uL);val lengths=listOf(192uL,1936uL,0x1b60c0uL)
 destinations.forEachIndexed{i,e->val actualA=addresses[i]+if(arm==82&&i==1)1uL else 0uL;val actualL=lengths[i]-if(arm==83&&i==1)1uL else 0uL;require(e.s("category")=="destination"&&e.u("index")==i.toULong()&&e.u("expected_address")==addresses[i]&&e.u("address")==actualA&&e.u("length")==actualL&&e.u("expected_length")==lengths[i]&&e.u("match")==if(actualA==addresses[i]&&actualL==lengths[i])1uL else 0uL)}
 val expectedCp=when(arm){in 76..77,84,85,88->4;86,89->1;else->0};val expectedAtomic=when(arm){in 76..77,84,85,88->4;78,79,86,89->1;else->0};val emittedCp=expectedCp+if(arm in 78..80)1 else 0;val cp=es.filter{it.kind=="loader-checkpoint"};require(cp.size==emittedCp&&cp.map{it.u("index")}==List(emittedCp){if(it<expectedCp)it.toULong() else expectedCp.toULong()});val pcs=listOf("gm_cl_cp0","gm_cl_cp1","gm_cl_cp2","gm_cl_cp3").map{elf.symbol(it)};val statuses=if(arm==77)listOf(-1,-2,-3,0)else listOf(192,0x1b60c0,1936,0);cp.forEachIndexed{i,e->val accepted=i<expectedCp;val index=if(accepted)i else expectedCp;val actualPc=if(arm==79&&!accepted)elf.symbol("gm_cl_bad_cp") else pcs[index];val expectedPc=if(arm==78&&!accepted)pcs[1] else actualPc;val actualOpcode=if(arm==79&&!accepted)0xaa0003e0uL else 0xd503201fuL;val actualTid=if(arm==80&&!accepted)e.u("tid") else pid;require((arm!=80||accepted||actualTid==model.u("fixture_worker"))&&e.u("tid")==actualTid&&e.u("signal")==5uL&&e.u("si_code")==4uL&&e.u("address")==actualPc&&e.u("pc")==actualPc&&e.u("opcode")==actualOpcode&&e.u("expected_pc")==expectedPc&&e.u("expected_opcode")==0xd503201fuL&&e.u("status").toUInt().toInt()==statuses[index]);val p=es.indexOf(e);require(es[p+1].kind=="loader-checkpoint-registers"&&regs(es[p+1]).pc==actualPc);if(arm==77&&index<3)require(regs(es[p+1]).x[0]==listOf(0xffffffffuL,0xfffffffeuL,0xfffffffduL)[index])}
 val statusEvents=es.filter{it.kind=="loader-status"};require(statusEvents.size==minOf(expectedCp,3));statusEvents.forEachIndexed{i,e->val signed=statuses[i].toLong().toULong();require(e.u("index")==i.toULong()&&e.u("width")==4uL&&e.u("actual")==signed&&e.u("expected")==signed&&e.u("match")==1uL)}
 // Exact captures and host binary witnesses.
 val expectedCaptureCount=when(arm){in 76..77,88->5;in 78..80,86,87,89->2;in 81..83->0;in 84..85->5;else->error("arm")};val captures=es.filter{it.kind=="loader-capture"};require(captures.size==expectedCaptureCount);val defs=listOf(Triple("entry-lsb",addresses[0],192),Triple("entry-adc",addresses[1],1936),Triple("terminal-lsb",addresses[0],192),Triple("terminal-adc",addresses[1],1936),Triple("terminal-vertical",addresses[2],0x1b60c0));val pats=listOf(0xa5uL,0x5auL,0x301uL,0x5auL,0x507uL);captures.forEachIndexed{i,e->val d=defs[i];require(e.u("index")==i.toULong()&&e.s("phase")== (if(i<2)"entry" else "terminal") &&e.s("name")=="loader-${d.first}.bin"&&e.u("address")==d.second&&e.u("length")==d.third.toULong()&&e.u("pattern")== (i+1).toULong());val full=d.third.toULong();val expectedCompleted=if(arm==84&&i==4)0x1b6000uL else full;val expectedResult=when{i==4&&arm==84->0x6000uL;i==4->0x60c0uL;else->full};val expectedChunks=if(i==4)28uL else 1uL;val expectedMatch=if(i==4&&arm in 84..85)0uL else 1uL;require(e.u("completed")==expectedCompleted&&e.u("result")==expectedResult&&e.u("chunks")==expectedChunks&&e.u("match")==expectedMatch)}
 val expectedFiles=mutableListOf<Pair<String,ByteArray>>();if(captures.size>=2)expectedFiles+=listOf("entry-lsb" to pattern(192,0,0xa5),"entry-adc" to pattern(1936,0,0x5a));if(captures.size>2){expectedFiles+=listOf("terminal-lsb" to pattern(192,3,1),"terminal-adc" to pattern(1936,0,0x5a));if(arm==84){expectedFiles+="terminal-vertical" to pattern(27*0x10000+0x6000,5,7)}else{val v=pattern(0x1b60c0,5,7);if(arm==85)v[v.lastIndex]=(v.last().toInt() xor 1).toByte();expectedFiles+="terminal-vertical" to v}};expectedFiles.forEach{checkFile("loader-$arm-${it.first}.bin",it.second)}
 // Arm 80 independently arms the stopped worker before private execution.
 val workerKinds=setOf("loader-worker-debug-before","loader-worker-before-registers","loader-worker-debug-arm-request","loader-worker-debug-arm-set","loader-worker-debug-arm-after","loader-worker-debug-registers","loader-worker-debug-ready");val workerEvents=es.filter{it.kind in workerKinds};if(arm==80){require(workerEvents.map{it.kind}==workerKinds.toList());val worker=model.u("fixture_worker");dump(workerEvents[0],0uL,0uL,false);require(regs(workerEvents[1]).tid==worker);dump(workerEvents[2],pcs[0],0x1e5uL,true);require(workerEvents[3].u("result")==0uL);dump(workerEvents[4],pcs[0],0x1e4uL,false);require(same(regs(workerEvents[1]),regs(workerEvents[5])));require(workerEvents[6].u("tid")==worker&&workerEvents[6].u("target")==pcs[0]&&workerEvents[6].u("opcode")==elf.word(pcs[0]))}else require(workerEvents.isEmpty())
 // Debug rotation starts from inherited tail CP2 and preserves registers.
 val before=es.filter{it.kind=="loader-debug-before"};val clearReq=es.filter{it.kind=="loader-debug-clear-request"};val clearSet=es.filter{it.kind=="loader-debug-clear-set"};val clearAfter=es.filter{it.kind=="loader-debug-clear-after"};val armReq=es.filter{it.kind=="loader-debug-arm-request"};val armSet=es.filter{it.kind=="loader-debug-arm-set"};val armAfter=es.filter{it.kind=="loader-debug-arm-after"};val ready=es.filter{it.kind=="loader-debug-ready"};val hasInitial=arm !in 81..83;val expectedBefore=expectedCp+(if(hasInitial)1 else 0);val expectedArms=(if(hasInitial)1 else 0)+expectedCp.coerceAtMost(3);require(before.size==expectedBefore&&clearReq.size==expectedCp&&clearSet.size==expectedCp&&clearAfter.size==expectedCp&&armReq.size==expectedArms&&armSet.size==armReq.size&&armAfter.size==armReq.size&&ready.size==armReq.size);if(hasInitial){dump(before.first(),0uL,0x1e5uL,false);val initialTarget=if(arm==79)elf.symbol("gm_cl_bad_cp") else pcs[0];dump(armReq[0],initialTarget,0x1e5uL,true);require(armSet[0].u("result")==0uL);dump(armAfter[0],initialTarget,0x1e4uL,false)};for(i in 0 until expectedCp){dump(before[i+1],pcs[i],0x1e4uL,false);dump(clearReq[i],0uL,0uL,true);require(clearSet[i].u("result")==0uL);dump(clearAfter[i],0uL,0x1e5uL,false);if(i<3){val ai=i+(if(hasInitial)1 else 0);dump(armReq[ai],pcs[i+1],0x1e5uL,true);require(armSet[ai].u("result")==0uL);dump(armAfter[ai],pcs[i+1],0x1e4uL,false)}};val debugRegs=es.filter{it.kind=="loader-debug-registers"};require(debugRegs.size==expectedCp+(if(hasInitial)1 else 0));ready.forEachIndexed{i,e->val checkpoint=i;val target=if(i==0&&arm==79)elf.symbol("gm_cl_bad_cp") else pcs[checkpoint];require(e.u("checkpoint")==checkpoint.toULong()&&e.u("tid")==pid&&e.u("target")==target&&e.u("opcode")==elf.word(target))};if(hasInitial){val tailRegs=regs(es.last{it.kind=="tail-checkpoint-registers"});require(same(tailRegs,regs(debugRegs[0])))};cp.take(expectedCp).forEachIndexed{i,e->require(same(regs(es[es.indexOf(e)+1]),regs(debugRegs[i+(if(hasInitial)1 else 0)])))}
 val accessRejects=es.filter{it.kind=="loader-access-rejected"};if(arm==86){val e=accessRejects.single();val q=es.indexOf(e);val f=es.subList(0,q).last{it.kind=="mapped-fault"};val r=regs(es.subList(0,q).last{it.kind=="fault-registers"});require(e.s("reason")=="unexpected-access"&&e.u("tid")==pid&&e.u("checkpoint")==1uL&&e.u("address")==mapping+8uL&&e.u("offset")==8uL&&e.u("pc")==readPc&&e.u("opcode")==0xb9400109uL&&f.u("signal")==11uL&&f.u("si_code")==2uL&&f.u("address")==mapping+8uL&&r.x[8]==f.u("address"))}else require(accessRejects.isEmpty());val loaderClones=es.filter{it.kind=="loader-clone"};if(arm==87){val c=loaderClones.single();require(c.u("parent_tid")==pid&&c.u("new_tid")!=pid)}else require(loaderClones.isEmpty())
 val reject=es.filter{it.kind=="loader-rejected"};if(a.outcome!="terminal"){val e=reject.single();val stage=when(arm){in 78..80->"trap";in 81..83->"entry";in 84..85->"terminal-vertical";else->"runtime"};val ae=when(arm){78->pcs[0] to pcs[1];79->elf.symbol("gm_cl_bad_cp") to elf.symbol("gm_cl_bad_cp");80->pcs[0] to pcs[0];81->1uL to 0uL;82->2uL to 0uL;83->3uL to 0uL;84,85->0uL to 0x1b60c0uL;86->8uL to 0uL;87->es.single{it.kind=="loader-clone"}.u("new_tid") to 0uL;89->1uL to 4uL;else->error("arm")};require(e.s("reason")==a.reason&&e.s("stage")==stage&&e.u("checkpoint")==expectedCp.toULong()&&e.u("captures")== (if(arm in setOf(84,85))4uL else captures.size.toULong())&&e.u("atomic")==expectedAtomic.toULong()&&e.u("actual")==ae.first&&e.u("expected")==ae.second)}else require(reject.isEmpty());val deadlines=es.filter{it.kind=="loader-deadline"};require(deadlines.size==if(a.outcome=="deadline")1 else 0);if(deadlines.isNotEmpty())require(deadlines.single().u("stopping_tid")==0uL&&deadlines.single().u("checkpoint")==1uL)
 val summary=es.single{it.kind=="loader-summary"};require(summary.u("checkpoints")==expectedCp.toULong()&&summary.u("captures")== (if(arm in setOf(84,85))4uL else captures.size.toULong())&&summary.u("atomic")==expectedAtomic.toULong()&&summary.u("old_executed")== (if(arm==88)1uL else 0uL) &&summary.u("modeled_reads")==0uL&&summary.u("modeled_writes")==0uL&&summary.u("clone_tid")==if(arm==87)es.single{it.kind=="loader-clone"}.u("new_tid") else 0uL)
 // Exact group convergence and cleanup.
 val converges=es.filter{it.kind=="loader-terminal-converge"};require(converges.size==if(arm in setOf(76,77,84,85,88))1 else 0);if(converges.isNotEmpty())require(converges.single().u("stopping_tid")==pid&&es.indexOf(converges.single())<es.indexOf(captures[2]))
 fun inventory(phase:String):Set<ULong>{val st=es.filter{it.kind=="thread-status"&&it.s("phase")==phase};val inv=es.single{it.kind=="thread-inventory"&&it.s("phase")==phase};val ids=st.map{it.u("tid")};require(ids.distinct().size==ids.size&&st.all{"read_error" !in it.f&&it.u("tgid")==pid&&it.u("tracer_pid")==observer&&it.u("state")==0x74uL});require(inv.u("pid")==pid&&inv.u("observer_pid")==observer&&inv.u("observed_count")==ids.size.toULong()&&inv.u("overflow")==0uL&&inv.u("error")==0uL);return ids.toSet()}
 val beforeTids=inventory("before-ready");val terminalTids=inventory("terminal");require(pid in beforeTids);val runtimeClones=es.filter{it.kind=="runtime-clone"}.map{it.u("new_tid")}.toSet();val tracked=es.filter{it.kind=="group-track"}.map{it.u("tid")};require(tracked.size==tracked.distinct().size&&tracked.toSet()==beforeTids+runtimeClones&&terminalTids==tracked.toSet());es.filter{it.kind=="runtime-clone"}.forEach{require(it.u("parent_tid") in tracked)};val reap=es.filter{it.kind=="group-reaped"};require(reap.size==tracked.size&&reap.map{it.u("tid")}.toSet()==tracked.toSet()&&reap.all{it.u("status")==9uL});val q=es.single{it.kind=="terminal-quiesce"};val stop=if(arm==89)0uL else if(reject.isNotEmpty())reject.single().u("tid") else pid;require(q.u("stopping_tid")==stop);val cleanup=es.single{it.kind=="group-cleanup"};require(cleanup.u("expected_count")==tracked.size.toULong()&&cleanup.u("reaped_count")==tracked.size.toULong()&&cleanup.u("wait_result").toLong()==-10L&&es.last()==cleanup);require(es.none{it.kind in setOf("error","group-failure","terminal-cleanup-deadline","unexpected-runtime-signal")})
}
if(args.size==2){val arm=args[1].toInt();verify(arms.single{it.arm==arm});println("schema_version = \"mho900-lab.calibration-loader-verification/1\"\nresult = \"accepted\"\narm = $arm");kotlin.system.exitProcess(0)}
require(text("result.toml").contains("mode = \"loadercontrol\"")&&text("result.toml").contains("inspection = \"completed\""));for(a in arms){require(text("loader-${a.arm}-verification.toml").contains("result = \"accepted\""));verify(a)}
val indexLines=Files.readAllLines(run.resolve("evidence-sha256.txt"));val indexed=indexLines.map{line->require(line.length>66&&line.substring(64,66)=="  ");val path=Path.of(line.substring(66)).toAbsolutePath().normalize();require(path.startsWith(run)&&Files.isRegularFile(path));require(hash(Files.readAllBytes(path))==line.take(64));path};require(indexed.distinct().size==indexed.size);val required=mutableSetOf("calibration-loader-candidate.toml","calibration-loader-controls.toml","group-control.elf","reference.tsv","spu-private.bin","adc-private.bin");for(a in arms){required+=listOf("loader-${a.arm}.toml","loader-${a.arm}-status.toml","loader-${a.arm}.elf");for(n in listOf("entry-lsb","entry-adc","terminal-lsb","terminal-adc","terminal-vertical")){val f="loader-${a.arm}-$n.bin";if(Files.exists(run.resolve(f)))required+=f}};require(required.all{n->run.resolve(n).toAbsolutePath().normalize() in indexed})
val pids=Regex("(?m)^([a-z0-9_]+) = (\\d+)$").findAll(text("loader-system-server.toml")).map{it.groupValues[2]}.toList();require(pids.size==16&&pids.distinct().size==1);require(text("loader-enforcing.txt").lineSequence().filter{it.isNotBlank()}.all{it.trim()=="Enforcing"}&&text("loader-packages.txt").isBlank());for(n in listOf("loader-processes-before.txt","loader-processes-after.txt"))require(!Regex("Sparrow|frida|group-observer").containsMatchIn(text(n)));println("schema_version = \"mho900-lab.calibration-loader-verification/1\"\nresult = \"accepted\"\nmode = \"loadercontrol\"\narms = 14")
