// Independently verify the calibration static contract against the pinned stock ELF.
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.HexFormat

require(args.size == 2) { "Usage: VerifyCalibrationContract.main.kts STOCK_ELF CONTRACT_DIRECTORY" }
val elfPath=Path.of(args[0]); val contractDir=Path.of(args[1])
fun sha(bytes:ByteArray)=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes))
fun sha(path:Path)=sha(Files.readAllBytes(path))
fun num(raw:String):Long { val s=raw.trim();require(s.matches(Regex("(?:-?[0-9]+|0x[0-9a-fA-F]+)"))){"bad integer $s"};return if(s.startsWith("0x"))s.drop(2).toLong(16) else s.toLong() }
fun bool(raw:String):Boolean=when(raw.trim()){ "true"->true;"false"->false;else->error("bad boolean $raw") }
fun str(raw:String):String { val s=raw.trim();require(s.length>=2&&s.first()=='"'&&s.last()=='"'){"bad string $s"};val out=StringBuilder();var i=1;while(i<s.lastIndex){val c=s[i++];if(c!='\\')out.append(c)else{require(i<s.lastIndex);when(val e=s[i++]){'\\'->out.append('\\');'"'->out.append('"');'n'->out.append('\n');'t'->out.append('\t');else->error("bad escape \\$e")}}};return out.toString() }
fun arr(raw:String):List<String>{val s=raw.trim();require(s.startsWith("[")&&s.endsWith("]")){"bad array $s"};val body=s.substring(1,s.lastIndex);if(body.isBlank())return emptyList();val out=mutableListOf<String>();var quoted=false;var escaped=false;var begin=0;for(i in body.indices){val c=body[i];if(escaped){escaped=false;continue};if(quoted&&c=='\\'){escaped=true;continue};if(c=='"')quoted=!quoted;if(c==','&&!quoted){out+=body.substring(begin,i).trim();begin=i+1}};require(!quoted&&!escaped);out+=body.substring(begin).trim();require(out.none(String::isEmpty));return out}
data class Tab(val kind:String,val line:Int,val array:Boolean,val v:LinkedHashMap<String,String> = linkedMapOf())
data class Doc(val root:LinkedHashMap<String,String>,val tabs:List<Tab>)
fun parse(path:Path):Doc { val root=linkedMapOf<String,String>();val tabs=mutableListOf<Tab>();var cur:Tab?=null
 Files.readAllLines(path).forEachIndexed{index,source->val line=source.trim();if(line.isEmpty()||line.startsWith("#"))return@forEachIndexed
  if(line.startsWith("[[")){require(line.endsWith("]]")){"bad array table line ${index+1}"};val k=line.substring(2,line.length-2).trim();require(k.matches(Regex("[a-z_][a-z0-9_.-]*")));cur=Tab(k,index+1,true);tabs+=cur!!;return@forEachIndexed}
  if(line.startsWith("[")){require(line.endsWith("]")&&!line.startsWith("[[")){"bad table line ${index+1}"};val k=line.substring(1,line.lastIndex).trim();require(k.matches(Regex("[a-z_][a-z0-9_.-]*")));require(tabs.none{it.kind==k&&!it.array}){"duplicate table $k"};cur=Tab(k,index+1,false);tabs+=cur!!;return@forEachIndexed}
  val eq=line.indexOf('=');require(eq>0){"bad assignment line ${index+1}"};val key=line.substring(0,eq).trim();require(key.matches(Regex("[a-z_][a-z0-9_.-]*")));val value=line.substring(eq+1).trim();require(value.isNotEmpty());val map=cur?.v?:root;require(map.put(key,value)==null){"duplicate $key line ${index+1}"}
 };return Doc(root,tabs)}

data class Seg(val file:Long,val virtual:Long,val fileSize:Long,val memorySize:Long)
data class Sec(val type:Int,val file:Long,val size:Long,val link:Int,val entry:Long)
data class Sym(val name:String,val value:Long,val size:Long,val section:Int)
data class Rel(val slot:Long,val type:Long,val symbol:Sym?)
class Elf(val raw:ByteArray){private val b=ByteBuffer.wrap(raw).order(ByteOrder.LITTLE_ENDIAN);private fun u16(p:Int)=b.getShort(p).toInt()and 0xffff;private fun u32(p:Int)=b.getInt(p).toLong()and 0xffffffffL;private fun u64(p:Int)=b.getLong(p);private val segs:List<Seg>;val symbols:Map<String,Sym>;val rels:Map<Long,Rel>
 init{require(raw.size>=64&&raw[0]==0x7f.toByte()&&String(raw,1,3)=="ELF"&&raw[4]==2.toByte()&&raw[5]==1.toByte()&&u16(18)==183){"not AArch64 ELF64 LE"};segs=(0 until u16(56)).map{u64(32).toInt()+it*u16(54)}.filter{u32(it)==1L}.map{Seg(u64(it+8),u64(it+16),u64(it+32),u64(it+40))};val secs=(0 until u16(60)).map{u64(40).toInt()+it*u16(58)}.map{Sec(u32(it+4).toInt(),u64(it+24),u64(it+32),u32(it+40).toInt(),u64(it+56))};fun readSymbols(s:Sec):List<Sym>{require(s.entry==24L);val strings=secs[s.link];return (0 until(s.size/s.entry).toInt()).map{i->val p=(s.file+i*s.entry).toInt();val start=(strings.file+u32(p)).toInt();var end=start;while(raw[end]!=0.toByte())end++;Sym(String(raw,start,end-start),u64(p+8),u64(p+16),u16(p+6))}};val all=secs.filter{it.type==11}.flatMap(::readSymbols);symbols=all.filter{it.name.isNotEmpty()}.groupBy{it.name}.mapValues{(name,list)->val d=list.filter{it.section!=0};require(d.map{it.value to it.size}.distinct().size<=1){"conflicting $name"};d.firstOrNull()?:list.first()};val rm=mutableMapOf<Long,Rel>();secs.filter{it.type==4}.forEach{s->val linked=readSymbols(secs[s.link]);repeat((s.size/s.entry).toInt()){i->val p=(s.file+i*s.entry).toInt();val info=u64(p+8);val si=(info ushr 32).toInt();val r=Rel(u64(p),info and 0xffffffffL,if(si==0)null else linked[si]);require(rm.put(r.slot,r)==null){"duplicate ELF relocation"}}};rels=rm}
 private fun off(va:Long,n:Int):Int{val s=segs.filter{va>=it.virtual&&va+n<=it.virtual+it.fileSize};require(s.size==1){"unmapped 0x${va.toString(16)}"};return(s.single().file+va-s.single().virtual).toInt()}
 fun bytes(va:Long,n:Int)=raw.copyOfRange(off(va,n),off(va,n)+n);fun word(va:Long)=ByteBuffer.wrap(bytes(va,4)).order(ByteOrder.LITTLE_ENDIAN).int.toLong()and 0xffffffffL
 fun loadContaining(va:Long,n:Long)=segs.single{va>=it.virtual&&va+n<=it.virtual+it.memorySize}
}

val pinned="4e7eb0bb81b6bcc6923ceff75fd259d41be555dccc6867e53ed7ee2ea3b2894e"
val elfBytes=Files.readAllBytes(elfPath);val elf=Elf(elfBytes);require(sha(elfBytes)==pinned){"stock ELF hash"}
fun file(name:String)=contractDir.resolve(name).also{require(Files.isRegularFile(it)){"missing $name"}}
fun doc(name:String)=parse(file(name))
fun tab(d:Doc,kind:String)=d.tabs.single{it.kind==kind&&!it.array}
fun tabs(d:Doc,kind:String)=d.tabs.filter{it.kind==kind&&it.array}
fun sval(t:Tab,k:String)=str(t.v.getValue(k));fun nval(t:Tab,k:String)=num(t.v.getValue(k))
fun decodeBranch(pc:Long,op:Long):Long {require((op ushr 26)==0x25L){"not BL at 0x${pc.toString(16)}"};var imm=op and 0x03ffffffL;if((imm and 0x02000000L)!=0L)imm=imm or -0x04000000L;return pc+(imm shl 2)}
fun decodePltSlot(pc:Long):Long {val adrp=elf.word(pc);val ldr=elf.word(pc+4);require((adrp and 0x9f00001fL)==0x90000010L&&((ldr ushr 22)and 0x3ffL)==0x3e5L){"PLT encoding 0x${pc.toString(16)}"};var imm=((adrp ushr 29)and 3L)or(((adrp ushr 5)and 0x7ffffL)shl 2);if((imm and 0x100000L)!=0L)imm=imm or -0x200000L;return (pc and -4096L)+(imm shl 12)+(((ldr ushr 10)and 0xfffL)shl 3)}
val result=doc("results.toml")
require(str(result.root.getValue("stock_library_sha256"))==pinned)
val pins=tabs(result,"artifacts").associate{sval(it,"path") to sval(it,"sha256")}
val componentNames=listOf("scope.toml","call-inventory.toml","dispatcher.toml","loaders.toml","checked-stream.toml","adc-initial-state.toml","algorithms-threads.toml","adc-parameters.toml","assets.toml")
for(n in componentNames){val p="experiments/calibration-static/$n";require(pins[p]==sha(file(n))){"artifact pin $n"}}
val scope=doc("scope.toml");require(str(scope.root.getValue("stock_library_sha256"))==pinned);require(bool(scope.root.getValue("parent_calls_complete")));require(!bool(scope.root.getValue("transitive_recovery_complete")));require(num(scope.root.getValue("inventory_ranges"))==22L&&num(scope.root.getValue("inventory_calls"))==381L);require(arr(scope.root.getValue("operation_classes")).map(::str).toSet()==setOf("STATIC-DETERMINED","RUNTIME-SELECTED","HARDWARE-RETURNED","ASYNCHRONOUS","UNKNOWN"));require(num(scope.root.getValue("earliest_hardware_call"))==0x33f038L);require(arr(scope.root.getValue("first_reference_fields")).map(::num)==listOf(0x8854L,0x8856L));require(!bool(scope.root.getValue("live_preload_record_established")))

val inv=doc("call-inventory.toml");require(str(inv.root.getValue("stock_library_sha256"))==pinned);require(!bool(inv.root.getValue("transitive_complete")))
val ranges=tabs(inv,"ranges");require(ranges.size==22);data class R(val name:String,val a:Long,val z:Long);val rmap=linkedMapOf<String,R>()
for(t in ranges){require(t.v.keys==setOf("name","address","size","sha256"));val name=sval(t,"name");val a=nval(t,"address");val size=nval(t,"size");require(size>0&&size<0x200000);require(rmap.put(name,R(name,a,a+size))==null){"duplicate range"};val s=requireNotNull(elf.symbols[name]){"symbol $name"};require(s.section!=0&&s.value==a&&s.size==size){"range $name"};require(sha(elf.bytes(a,size.toInt()))==sval(t,"sha256")){"range hash $name"}}
val requiredRanges=setOf("_ZN12CCalibration4InitEv","_ZN8RQThread5startEv","_Z12Drv_GetScopev","_ZN9CDrvScope14GetCalibrationEv","_ZN16CCalibration_ADC11LoadCalDataEv","_ZN16CCalibration_ADC15SetADCParameterEj","DrvCalibration_CalAdcSyncDelay","_ZN16CCalibration_ADC14CalAdcDataLineEPj","_ZN16CCalibration_ADC13LoadAdcIDelayEbPj","DevAcquireSPU_CalAdcCoreAlign","_ZN16CCalibration_ADC7CalQADCEv");require(requiredRanges.all{it in rmap}){"required range"}
val calls=tabs(inv,"calls");require(calls.size==381);val callKeys=mutableSetOf<Pair<String,Long>>()
for(t in calls){val owner=sval(t,"owner");val pc=nval(t,"pc");val op=nval(t,"opcode");require(callKeys.add(owner to pc)){"duplicate call"};val ro=requireNotNull(rmap[owner]){"owner $owner"};require(pc in ro.a until ro.z){"parent coverage $owner"};require(elf.word(pc)==op){"call opcode 0x${pc.toString(16)}"};val target=decodeBranch(pc,op);require(target==nval(t,"branch_target")){"call target 0x${pc.toString(16)}"};require(sval(t,"form")=="BL"){"call form"};val symbol=sval(t,"symbol");val resolved=nval(t,"resolved_target");val symbolDefined=symbol!="UNRESOLVED"&&elf.symbols[symbol]?.section!=0;require(bool(t.v.getValue("defined"))==symbolDefined){"defined flag $symbol"};require(bool(t.v.getValue("expanded"))==rmap.values.any{it.a==resolved}){"expanded flag $symbol"};if("relocation_slot" in t.v){val slot=nval(t,"relocation_slot");require(decodePltSlot(target)==slot){"decoded PLT slot $symbol"};val rel=requireNotNull(elf.rels[slot]){"relocation"};require(rel.symbol?.name==symbol){"PLT symbol $symbol"};val sym=requireNotNull(elf.symbols[symbol]);if(sym.section!=0)require(resolved==sym.value){"resolved $symbol"}}else if(symbol=="UNRESOLVED"){require(resolved==target){"unresolved target"}}else{val sym=requireNotNull(elf.symbols[symbol]);require(sym.section!=0&&resolved==sym.value&&target==resolved){"direct symbol $symbol"}}
}
val scannedKeys=mutableSetOf<Pair<String,Long>>();for(r in rmap.values){var scanPc=r.a;while(scanPc<r.z){val op=elf.word(scanPc);if((op ushr 26)==0x25L)scannedKeys+=r.name to scanPc;scanPc+=4}};require(scannedKeys==callKeys){"complete selected-range call coverage"};val init=rmap.getValue("_ZN12CCalibration4InitEv")

val dispatch=doc("dispatcher.toml");require(str(dispatch.root.getValue("stock_library_sha256"))==pinned);val nodes=tabs(dispatch,"nodes");val edges=tabs(dispatch,"edges");require(nodes.size==24&&edges.size==24);val ids=mutableSetOf<String>();for(t in nodes){val id=sval(t,"id");require(ids.add(id));val p=nval(t,"pc");val op=nval(t,"opcode");require(elf.word(p)==op){"dispatcher opcode $id"};if((op ushr 26)==0x25L&&id !in setOf("get_scope","get_calibration")){val matching=calls.any{nval(it,"pc")==p&&nval(it,"opcode")==op};require(matching){"dispatcher call absent $id"}};require(sval(t,"classification") in setOf("STATIC-DETERMINED","RUNTIME-SELECTED","HARDWARE-RETURNED","ASYNCHRONOUS","UNKNOWN"))}
val edgeTriples=edges.map{Triple(sval(it,"from"),sval(it,"to"),sval(it,"condition"))};val expectedEdges=setOf(Triple("get_scope","get_calibration","callee returns normally"),Triple("get_calibration","initialize_buffers","callee returns normally"),Triple("initialize_buffers","load_lsb","callee returns normally"),Triple("load_lsb","load_vertical","callee returns normally"),Triple("load_vertical","load_adc","callee returns normally"),Triple("load_adc","apply_adc_zero","callee returns normally"),Triple("apply_adc_zero","load_afe_zero","callee returns normally"),Triple("load_afe_zero","load_afe_bandwidth","callee returns normally"),Triple("load_afe_bandwidth","load_clock","callee returns normally"),Triple("load_clock","load_ext","callee returns normally"),Triple("load_ext","load_ddr","callee returns normally"),Triple("load_ddr","configure_ddr","signed load result>=1"),Triple("load_ddr","load_afg","signed load result<1"),Triple("configure_ddr","load_afg","callee returns normally"),Triple("load_afg","load_stray","callee returns normally"),Triple("load_stray","load_la","callee returns normally"),Triple("load_la","sync_delay","callee returns normally"),Triple("sync_delay","data_line","callee returns normally"),Triple("data_line","input_delay","callee returns normally"),Triple("input_delay","core_align","callee returns normally"),Triple("core_align","qadc","callee returns normally"),Triple("qadc","thread_start","callee returns normally"),Triple("thread_start","return","callee returns and stack canary unchanged"),Triple("thread_start","canary_failure","callee returns and stack canary differs"));require(edgeTriples.size==expectedEdges.size&&edgeTriples.toSet()==expectedEdges){"dispatcher edge contract"};val loops=tab(dispatch,"loops");require(arr(loops.v.getValue("afg_selectors")).map(::num)==listOf(1L,2L));require(num(loops.v.getValue("afg_stride"))==0x290L);require(arr(loops.v.getValue("adc_stray_selectors")).map(::num)==listOf(0L,1L,2L,3L));val lpcs=arr(loops.v.getValue("pcs")).map(::num);val lops=arr(loops.v.getValue("opcodes")).map(::num);require(lpcs.size==6&&lpcs.zip(lops).all{elf.word(it.first)==it.second}){"loop witnesses"}
val storage=tab(dispatch,"storage");require(nval(storage,"scope_relative_address")==0x10bee40L&&nval(storage,"adc_record_relative_address")==0x10cd734L&&nval(storage,"adc_record_bytes")==1936L&&bool(storage.v.getValue("record_in_zero_fill"))&&!bool(storage.v.getValue("live_state_proven")));arr(storage.v.getValue("get_scope_pcs")).map(::num).zip(arr(storage.v.getValue("get_scope_opcodes")).map(::num)).forEach{require(elf.word(it.first)==it.second)}

val loaders=doc("loaders.toml");require(str(loaders.root.getValue("stock_elf_sha256"))==pinned);val parent=tab(loaders,"parent");require(nval(parent,"start")==init.a&&nval(parent,"size")==init.z-init.a&&sval(parent,"range_sha256")==sha(elf.bytes(init.a,(init.z-init.a).toInt())));val loaderContract=mapOf("vertical_lsb" to Triple(192L,"/rigol/data/cal_lsb.hex","/rigol/data/default/cal_lsb.hex"),"vertical" to Triple(0x1b60c0L,"/rigol/data/cal_vertical.hex","/rigol/data/default/cal_vertical.hex"),"adc" to Triple(1936L,"/rigol/data/cal_adc.hex","/rigol/data/default/cal_adc.hex"),"afe_zero" to Triple(560L,"/rigol/data/cal_afe_zero.hex","/rigol/data/default/cal_afe_zero.hex"),"afe_bandwidth" to Triple(320L,"/rigol/data/cal_afe_bandwidth.hex","/rigol/data/default/cal_afe_bandwidth.hex"),"clock" to Triple(8L,"/rigol/data/cal_clock.hex","/rigol/data/default/cal_clock.hex"),"external" to Triple(160L,"/rigol/data/cal_ext.hex",""),"ddr" to Triple(48L,"/rigol/data/cal_ddr.hex","/rigol/data/default/cal_ddr.hex"),"afg" to Triple(320L,"channel-formatted-five-files",""),"adc_stray" to Triple(-1L,"/rigol/data/AdcStray%d.hex",""),"la" to Triple(8L,"/rigol/data/cal_la.hex","/rigol/data/default/cal_la.hex"));val ls=tabs(loaders,"loaders");require(ls.size==loaderContract.size);for(t in ls){val id=sval(t,"id");val e=requireNotNull(loaderContract[id]);val name=sval(t,"symbol");val rr=requireNotNull(rmap[name]);require(nval(t,"start")==rr.a&&nval(t,"size")==rr.z-rr.a&&sval(t,"range_sha256")==sha(elf.bytes(rr.a,(rr.z-rr.a).toInt())));require(nval(t,"bytes")==e.first&&sval(t,"primary")==e.second&&sval(t,"fallback")==e.third);val cpc=nval(t,"call_pc");require(calls.any{nval(it,"pc")==cpc&&sval(it,"symbol")==name}){"loader call $id"}}
for(t in tabs(loaders,"constants")){val a=nval(t,"address");val n=nval(t,"length").toInt();require(sha(elf.bytes(a,n))==sval(t,"sha256")){"constant ${sval(t,"id")}"}}

val cs=doc("checked-stream.toml");require(str(cs.root.getValue("stock_elf_sha256"))==pinned);val ctl=tab(cs,"loader");val csym=requireNotNull(elf.symbols[sval(ctl,"symbol")]);require(csym.section!=0&&nval(ctl,"start")==csym.value&&nval(ctl,"size")==csym.size&&sval(ctl,"range_sha256")==sha(elf.bytes(csym.value,csym.size.toInt())));require(nval(ctl,"header_bytes")==28L&&nval(ctl,"header_body_bytes")==20L);val fields=tabs(cs,"format_fields");require(fields.map{nval(it,"offset")}.toSet()==setOf(0L,4L,8L,12L,20L,24L));require(fields.associate{nval(it,"offset") to nval(it,"width")}==mapOf(0L to 4L,4L to 4L,8L to 4L,12L to 8L,20L to 4L,24L to 4L))

val initial=doc("adc-initial-state.toml");require(str(initial.root.getValue("stock_elf_sha256"))==pinned);require(!bool(initial.root.getValue("constructor_defines_loaded_record"))&&bool(initial.root.getValue("image_initial_zero_proven"))&&!bool(initial.root.getValue("live_preload_zero_proven")));val seg=tab(initial,"load_segment");val rec=tab(initial,"record_identity");val actualSeg=elf.loadContaining(nval(rec,"link_time_start"),nval(rec,"link_time_end_exclusive")-nval(rec,"link_time_start"));require(nval(seg,"virtual_address")==actualSeg.virtual&&nval(seg,"file_size")==actualSeg.fileSize&&nval(seg,"memory_size")==actualSeg.memorySize&&nval(seg,"file_backed_end")==actualSeg.virtual+actualSeg.fileSize);require(nval(rec,"link_time_start")==0x10cd734L&&nval(rec,"link_time_end_exclusive")==0x10cdec4L&&nval(rec,"link_time_start")>=actualSeg.virtual+actualSeg.fileSize&&nval(rec,"link_time_end_exclusive")<=actualSeg.virtual+actualSeg.memorySize);val consumed=tabs(initial,"first_consumed_fields");require(consumed.size==2);val expectedFields=mapOf(0x33f024L to 0x8854L,0x33f048L to 0x8856L);for(t in consumed){val lp=nval(t,"load_pc");require(nval(t,"adc_offset")==expectedFields[lp]&&nval(t,"width")==2L&&bool(t.v.getValue("signed")));require(elf.word(lp) in setOf(0x78ea6901L,0x78e86921L))}

val adc=doc("adc-parameters.toml");require(str(adc.root.getValue("stock_elf_sha256"))==pinned);require(num(adc.root.getValue("call_pc"))==0x333ba8L&&elf.word(0x333ba8)==0x97fb9b9eL&&num(adc.root.getValue("mode"))==0L);require(sha(elf.bytes(num(adc.root.getValue("start")),num(adc.root.getValue("byte_length")).toInt()))==str(adc.root.getValue("range_sha256")));val steps=tabs(adc,"steps");require(steps.map{nval(it,"order")}==(0L..7L).toList());require(nval(steps[0],"call_pc")==0x33f038L&&nval(steps[1],"call_pc")==0x33f058L);require(nval(steps[3],"helper_call_count")==16L&&nval(steps[5],"call_count")==16L);val transport=tab(adc,"adc_transport");require(nval(transport,"set_adc_reg")==0x27e8a8L&&nval(transport,"dev_adc_write")==0x2717c8L&&nval(transport,"register_offset")==0x3000L&&nval(transport,"write_count_per_call")==2L&&nval(transport,"inter_write_delay_us")==100L)


val refinements=doc("review-refinements.toml");val gain=tab(refinements,"gain_index_table");require(nval(gain,"address")==0x99d210L&&nval(gain,"entry_count")==10L&&nval(gain,"entry_width")==8L&&nval(gain,"element_width")==4L&&bool(gain.v.getValue("signed"))&&nval(gain,"byte_length")==80L);require(sha(elf.bytes(0x99d210,80))==sval(gain,"sha256")){"gain index table hash"};val expectedGain=listOf(0L,0L,1L,1L,2L,2L,3L,3L,0L,1L,0L,2L,0L,3L,1L,2L,1L,3L,2L,3L);val actualGain=(0 until 20).map{ByteBuffer.wrap(elf.bytes(0x99d210L+it*4L,4)).order(ByteOrder.LITTLE_ENDIAN).int.toLong()};require(actualGain==expectedGain){"gain index entries"};val gainText=gain.v.getValue("entries").replace(" ","");require(Regex("\\[(?:\\[-?[0-9]+,-?[0-9]+\\],){9}\\[-?[0-9]+,-?[0-9]+\\]\\]").matches(gainText)){"gain entry shape"};val suppliedGain=Regex("-?[0-9]+").findAll(gainText).map{it.value.toLong()}.toList();require(suppliedGain==expectedGain){"supplied gain entries"};require(nval(gain,"mode_zero_word_count")==16L&&nval(gain,"mode_zero_source_offset")==0x8cd4L&&bool(gain.v.getValue("mode_zero_source_contiguous")));val thread=tab(refinements,"thread_order");require(nval(thread,"thread_constructor_call_pc")==0x252978L&&nval(thread,"active_flag_store_pc")==0x2529a8L&&nval(thread,"detach_call_pc")==0x2529b8L&&nval(thread,"worker_entry")==0x33531cL&&!bool(thread.v.getValue("active_flag_precedes_worker_entry_proven")));require(elf.word(0x252978)==0x9400003aL&&elf.word(0x2529a8)==0x39002109L&&elf.word(0x2529b8)==0x97feea62L)


val candidate=doc("loader-candidate.toml");require(str(candidate.root.getValue("stock_elf_sha256"))==pinned&&str(candidate.root.getValue("stage"))=="reviewed-proposal"&&!bool(candidate.root.getValue("implementation_performed")));val layout=tab(candidate,"object_layout");val scopeObject=nval(layout,"scope");val calibration=scopeObject+nval(layout,"calibration_offset_from_scope");val adcObject=calibration+nval(layout,"adc_offset_from_calibration");val verticalObject=calibration+nval(layout,"vertical_offset_from_calibration");require(calibration==nval(layout,"calibration")&&adcObject==nval(layout,"adc")&&verticalObject==nval(layout,"vertical")){"candidate object arithmetic"};val destinationObjects=mapOf("lsb" to verticalObject,"vertical" to verticalObject,"adc" to adcObject);for(t in tabs(candidate,"destinations")){val id=sval(t,"id");val base=destinationObjects.getValue(id)+nval(t,"owner_offset");val length=nval(t,"length");require(nval(t,"base")==base&&nval(t,"end_exclusive")==base+length){"candidate destination $id"}}
val candidateCalls=tabs(candidate,"calls");require(candidateCalls.size==6);for(t in candidateCalls){val pc=nval(t,"pc");val op=nval(t,"opcode");require(elf.word(pc)==op);val plt=decodeBranch(pc,op);val slot=decodePltSlot(plt);require(slot==nval(t,"got_slot")){"candidate PLT slot"};val rel=requireNotNull(elf.rels[slot]);val symbol=sval(t,"symbol");require(rel.symbol?.name==symbol&&elf.symbols.getValue(symbol).value==nval(t,"target")){"candidate target"}}
val checkpointContract=mapOf(0L to Pair(0x2e57f8L,0x97fc6696L),1L to Pair(0x333b78L,0xb90077e0L),2L to Pair(0x333b84L,0xb90077e0L),3L to Pair(0x333b9cL,0xb90077e0L),4L to Pair(0x333ba8L,0x97fb9b9eL));val checkpoints=tabs(candidate,"checkpoints");require(checkpoints.size==5);for(t in checkpoints){val expected=checkpointContract.getValue(nval(t,"order"));require(nval(t,"pc")==expected.first&&nval(t,"opcode")==expected.second&&elf.word(expected.first)==expected.second){"candidate checkpoint"}}

println("schema_version = \"mho900-lab.calibration-contract-verification/1\"")
println("result = \"accepted\"")
println("stock_elf_sha256 = \"$pinned\"")
println("ranges = ${ranges.size}\ncalls = ${calls.size}\ndispatcher_nodes = ${nodes.size}\ndispatcher_edges = ${edges.size}\nloaders = ${ls.size}")
println("verified = \"ELF identity, range symbols and bytes, decoded direct calls and PLT relocations, parent call coverage, dispatcher loops and edges, loader ranges paths sizes constants, checked-stream widths, BSS zero-fill placement, and early ADC signed fields\"")
println("limit = \"Semantic prose, filesystem outcomes, live pre-load state, hardware completion, unexpanded calibration algorithms, and asynchronous worker effects remain outside static verification\"")
