// Independently verify a remaining-initialization grammar against the pinned stock ELF.
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.HexFormat

require(args.size == 2) { "Usage: VerifyRemainingInit.main.kts STOCK_ELF GRAMMAR" }
val elfPath = Path.of(args[0]); val grammarPath = Path.of(args[1])
fun sha(bytes: ByteArray) = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes))
fun sha(path: Path) = sha(Files.readAllBytes(path))
fun number(s: String): Long { val v=s.trim(); require(v.matches(Regex("(?:0x[0-9a-fA-F]+|[0-9]+)"))){"bad integer $v"}; return if(v.startsWith("0x"))v.drop(2).toLong(16) else v.toLong() }
fun string(s: String): String { val v=s.trim(); require(v.length>=2&&v.first()=='"'&&v.last()=='"'){"bad string $v"}; val b=StringBuilder(); var i=1; while(i<v.lastIndex){ val c=v[i++]; if(c!='\\')b.append(c) else { require(i<v.lastIndex); when(val e=v[i++]){'\\'->b.append('\\');'"'->b.append('"');'n'->b.append('\n');'t'->b.append('\t');else->error("bad escape \\$e") } } }; return b.toString() }
fun array(s:String):List<String>{val v=s.trim();require(v.startsWith("[")&&v.endsWith("]")){"bad array $v"};val body=v.substring(1,v.length-1);if(body.isBlank())return emptyList();val out=mutableListOf<String>();var quoted=false;var escape=false;var start=0;for(i in body.indices){val c=body[i];if(escape){escape=false;continue};if(c=='\\'&&quoted){escape=true;continue};if(c=='"')quoted=!quoted;if(c==','&&!quoted){out+=body.substring(start,i).trim();start=i+1}};require(!quoted&&!escape){"unterminated array"};out+=body.substring(start).trim();require(out.none{it.isEmpty()});return out}
data class Table(val kind:String,val line:Int,val values:LinkedHashMap<String,String> = linkedMapOf())
data class Doc(val root:LinkedHashMap<String,String>,val tables:List<Table>)
fun parse(path:Path):Doc{val root=linkedMapOf<String,String>();val tables=mutableListOf<Table>();var current:Table?=null;Files.readAllLines(path).forEachIndexed{index,raw->val line=raw.trim();if(line.isEmpty()||line.startsWith("#"))return@forEachIndexed;if(line.startsWith("[[")){require(line.endsWith("]]")){"bad table line ${index+1}"};val kind=line.substring(2,line.length-2).trim();require(kind.matches(Regex("[a-z_][a-z0-9_]*"))){"bad table $kind"};current=Table(kind,index+1);tables+=current!!;return@forEachIndexed};val eq=line.indexOf('=');require(eq>0){"bad assignment line ${index+1}"};val key=line.substring(0,eq).trim();require(key.matches(Regex("[a-z_][a-z0-9_]*"))){"bad key $key"};val value=line.substring(eq+1).trim();require(value.isNotEmpty());val map=current?.values?:root;require(map.put(key,value)==null){"duplicate $key line ${index+1}"}}
 return Doc(root,tables)}

data class Segment(val file:Long,val virtual:Long,val fileSize:Long)
data class Section(val type:Int,val file:Long,val size:Long,val link:Int,val entry:Long)
data class Symbol(val name:String,val value:Long,val size:Long,val section:Int)
data class Relocation(val slot:Long,val type:Long,val symbol:Symbol?)
class Elf(val bytes:ByteArray){private val b=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);private fun u16(p:Int)=b.getShort(p).toInt()and 0xffff;private fun u32(p:Int)=b.getInt(p).toLong()and 0xffffffffL;private fun u64(p:Int)=b.getLong(p);private val segments:List<Segment>;val symbols:Map<String,Symbol>;val relocations:Map<Long,Relocation>
 init{require(bytes.size>=64&&bytes[0]==0x7f.toByte()&&String(bytes,1,3)=="ELF"&&bytes[4]==2.toByte()&&bytes[5]==1.toByte()&&u16(18)==183){"not AArch64 ELF64 LE"};segments=(0 until u16(56)).map{u64(32).toInt()+it*u16(54)}.filter{u32(it)==1L}.map{Segment(u64(it+8),u64(it+16),u64(it+32))};val sections=(0 until u16(60)).map{u64(40).toInt()+it*u16(58)}.map{Section(u32(it+4).toInt(),u64(it+24),u64(it+32),u32(it+40).toInt(),u64(it+56))};fun syms(s:Section):List<Symbol>{require(s.entry==24L);val strings=sections[s.link];return (0 until (s.size/s.entry).toInt()).map{i->val p=(s.file+i*s.entry).toInt();val begin=(strings.file+u32(p)).toInt();var end=begin;while(bytes[end]!=0.toByte())end++;Symbol(String(bytes,begin,end-begin),u64(p+8),u64(p+16),u16(p+6))}};val all=sections.filter{it.type==11}.flatMap(::syms);symbols=all.filter{it.name.isNotEmpty()}.groupBy{it.name}.mapValues{(name,list)->val defined=list.filter{it.section!=0};require(defined.map{it.value to it.size}.distinct().size<=1){"conflicting symbol $name"};defined.firstOrNull()?:list.first()};val rs=mutableMapOf<Long,Relocation>();sections.filter{it.type==4}.forEach{s->require(s.entry>=24);val linked=syms(sections[s.link]);repeat((s.size/s.entry).toInt()){i->val p=(s.file+i*s.entry).toInt();val info=u64(p+8);val si=(info ushr 32).toInt();val r=Relocation(u64(p),info and 0xffffffffL,if(si==0)null else linked[si]);require(rs.put(r.slot,r)==null){"duplicate relocation ${r.slot}"}}};relocations=rs}
 private fun offset(address:Long,size:Int):Int{val found=segments.filter{address>=it.virtual&&address+size<=it.virtual+it.fileSize};require(found.size==1){"address outside one file segment 0x${address.toString(16)}"};return(found.single().file+address-found.single().virtual).toInt()}
 fun bytes(address:Long,size:Int)=bytes.copyOfRange(offset(address,size),offset(address,size)+size)
 fun word(address:Long)=ByteBuffer.wrap(bytes(address,4)).order(ByteOrder.LITTLE_ENDIAN).int.toLong()and 0xffffffffL}

val doc=parse(grammarPath);val elfBytes=Files.readAllBytes(elfPath);val elf=Elf(elfBytes)
val pinned="4e7eb0bb81b6bcc6923ceff75fd259d41be555dccc6867e53ed7ee2ea3b2894e"
require(doc.root.keys==setOf("schema_version","stock_library_sha256","method","entry","candidate_semantics")){"root fields"}
require(sha(elfBytes)==pinned){"stock hash"};require(string(requireNotNull(doc.root["schema_version"]))=="mho900-lab.remaining-init-grammar/1");require(string(requireNotNull(doc.root["stock_library_sha256"]))==pinned);require(string(requireNotNull(doc.root["method"])).isNotBlank());require(string(requireNotNull(doc.root["candidate_semantics"])).isNotBlank());val entry=string(requireNotNull(doc.root["entry"]));require(entry=="SCU")
val allowedTables=setOf("ranges","bindings","nodes","edges","candidate_writes");require(doc.tables.all{it.kind in allowedTables}){"unknown table"}

val ranges=doc.tables.filter{it.kind=="ranges"};require(ranges.isNotEmpty());val rangeNames=mutableSetOf<String>();for(t in ranges){require(t.values.keys==setOf("name","address","size","sha256")){"range fields line ${t.line}"};val name=string(t.values.getValue("name"));require(rangeNames.add(name)){"duplicate range $name"};val address=number(t.values.getValue("address"));val size=number(t.values.getValue("size"));require(size in 1..1048576);val symbol=elf.symbols[name];if(symbol!=null&&symbol.section!=0){require(symbol.value==address&&symbol.size==size){"symbol range $name"}};require(sha(elf.bytes(address,size.toInt()))==string(t.values.getValue("sha256"))){"range hash $name"}}
val requiredRanges=setOf("Dev_Init","_Z8Drv_Initb","DevSystemSCU_Init","Dev_WriteCommand","Dev_GetHardwareVersion","uartXSetup","DevLaDisplaySpu_SetAccRst","DevSystemSCU_GetVersion");require(rangeNames.containsAll(requiredRanges)){"missing required range"}

val bindings=doc.tables.filter{it.kind=="bindings"};require(bindings.isNotEmpty());val bindingSlots=mutableSetOf<Long>();for(t in bindings){require(t.values.keys==setOf("slot","type","symbol","target")){"binding fields line ${t.line}"};val slot=number(t.values.getValue("slot"));require(bindingSlots.add(slot)){"duplicate binding slot"};val r=requireNotNull(elf.relocations[slot]){"missing ELF relocation 0x${slot.toString(16)}"};val symbol=string(t.values.getValue("symbol"));require(r.type==number(t.values.getValue("type"))&&r.symbol?.name==symbol&&r.symbol.value==number(t.values.getValue("target"))){"binding mismatch $symbol"}}
require(setOf(0xb8cf08L,0xb8d830L,0xb8e020L,0xb8e068L,0xb8e118L).all{it in bindingSlots}){"missing state binding"}

val classes=setOf("STATIC-DETERMINED","RUNTIME-SELECTED","HARDWARE-RETURNED","ASYNCHRONOUS","UNKNOWN")
val nodes=doc.tables.filter{it.kind=="nodes"};require(nodes.isNotEmpty());val nodeById=linkedMapOf<String,Table>();for(t in nodes){require(t.values.keys==setOf("id","classification","operation","semantics","pcs","opcodes","inputs")){"node fields line ${t.line}"};val id=string(t.values.getValue("id"));require(id.matches(Regex("[A-Z][A-Z0-9_]*"))&&nodeById.put(id,t)==null){"duplicate/bad node $id"};require(string(t.values.getValue("classification"))in classes){"classification $id"};require(string(t.values.getValue("operation")).isNotEmpty()&&string(t.values.getValue("semantics")).isNotEmpty());val pcs=array(t.values.getValue("pcs")).map(::number);val opcodes=array(t.values.getValue("opcodes")).map(::number);require(pcs.isNotEmpty()&&pcs.size==opcodes.size){"pc/opcode shape $id"};pcs.zip(opcodes).forEach{(pc,opcode)->require(elf.word(pc)==opcode){"opcode $id at 0x${pc.toString(16)}"}};array(t.values.getValue("inputs")).forEach(::string)}
val exactNodes=setOf("SCU","BOARD_OPEN","BOARD_FRAME","BOARD_WRITE","BOARD_CLOSE","EXIT","RESET_SELECT","GD32_FD","GPIO_OPEN","GPIO_READ","GPIO_CLOSE","GD32_PATH","GD32_OPEN","GD32_SETUP","GD32_WRITE","GD32_VERSION","GD32_DELAY","LA","VERSION4","VERSION0","VERSION_COMPOSE","VERSION_HW","VERSION_LOG","DAC_TIME","DDR_SELECT","DDR_BODY","TRUE_INIT");require(nodeById.keys==exactNodes){"node ids"}
val hardware=setOf("GPIO_READ","GD32_VERSION","VERSION4","VERSION0","VERSION_HW");require(hardware.all{nodeById[it]?.let{n->string(n.values.getValue("classification"))=="HARDWARE-RETURNED"}==true}){"hardware-returned nodes"}
val gpio=requireNotNull(nodeById["GPIO_READ"]);require(string(gpio.values.getValue("operation"))=="READ1"){"GPIO operation"};val gpioPcs=array(gpio.values.getValue("pcs")).map(::number).toSet();require(gpioPcs.containsAll(setOf(0x2ad5b0,0x2ad5e4,0x2ad5e8,0x2ad5ec))){"GPIO ABI PCs"}

data class Edge(val from:String,val to:String,val condition:String)
val edges=doc.tables.filter{it.kind=="edges"}.map{t->require(t.values.keys==setOf("from","to","condition"));Edge(string(t.values.getValue("from")),string(t.values.getValue("to")),string(t.values.getValue("condition")))}
require(edges.isNotEmpty()&&edges.distinct().size==edges.size){"empty/duplicate edges"};require(edges.all{it.from in nodeById&&it.to in nodeById&&it.condition.isNotBlank()}){"edge reference/condition"}
val exactEdges=setOf("SCU|BOARD_OPEN","BOARD_OPEN|RESET_SELECT","BOARD_OPEN|BOARD_FRAME","BOARD_FRAME|BOARD_WRITE","BOARD_WRITE|EXIT","BOARD_WRITE|BOARD_CLOSE","BOARD_CLOSE|RESET_SELECT","RESET_SELECT|GD32_FD","RESET_SELECT|TRUE_INIT","GD32_FD|GPIO_OPEN","GD32_FD|GD32_WRITE","GPIO_OPEN|LA","GPIO_OPEN|GPIO_READ","GPIO_READ|GPIO_CLOSE","GPIO_CLOSE|LA","GPIO_CLOSE|GD32_PATH","GD32_PATH|GD32_OPEN","GD32_OPEN|LA","GD32_OPEN|GD32_SETUP","GD32_OPEN|GD32_WRITE","GD32_SETUP|LA","GD32_SETUP|GD32_WRITE","GD32_WRITE|LA","GD32_WRITE|GD32_VERSION","GD32_VERSION|GD32_DELAY","GD32_DELAY|LA","LA|VERSION4","VERSION4|VERSION0","VERSION0|VERSION_COMPOSE","VERSION_COMPOSE|VERSION_HW","VERSION_HW|VERSION_LOG","VERSION_LOG|DAC_TIME","DAC_TIME|DDR_SELECT","DDR_SELECT|DDR_BODY");require(edges.map{"${it.from}|${it.to}"}.toSet()==exactEdges){"flattened/missing/extra branch edge"}
val reached=mutableSetOf(entry);while(true){val old=reached.size;edges.filter{it.from in reached}.forEach{reached+=it.to};if(reached.size==old)break};require(reached==nodeById.keys){"unreachable nodes ${nodeById.keys-reached}"}

data class Candidate(val ordinal:Long,val node:String,val offset:Long,val value:Long,val condition:String)
val candidates=doc.tables.filter{it.kind=="candidate_writes"}.map{t->require(t.values.keys==setOf("ordinal","node","offset","value","condition"));Candidate(number(t.values.getValue("ordinal")),string(t.values.getValue("node")),number(t.values.getValue("offset")),number(t.values.getValue("value")),string(t.values.getValue("condition")))}
val exact=listOf(Candidate(0,"SCU",0x4004,0x80000000,"x"),Candidate(1,"SCU",0x4004,0,"x"),Candidate(2,"LA",0x7034,1,"x"),Candidate(3,"LA",0x7034,0,"x"),Candidate(4,"DAC_TIME",0x1428,0x646e,"x"));require(candidates.size==exact.size);candidates.zip(exact).forEach{(a,e)->require(a.ordinal==e.ordinal&&a.node==e.node&&a.offset==e.offset&&a.value==e.value&&a.condition.isNotBlank()){"candidate ${a.ordinal}"};require(a.node in nodeById)}

println("schema_version = \"mho900-lab.remaining-init-verification/1\"")
println("result = \"accepted\"")
println("stock_library_sha256 = \"$pinned\"")
println("grammar_sha256 = \"${sha(grammarPath)}\"")
println("ranges = ${ranges.size}\nbindings = ${bindings.size}\nnodes = ${nodes.size}\nedges = ${edges.size}\ncandidate_writes = ${candidates.size}")
