// Independently verify an initialization-tail grammar against the pinned stock ELF.
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.file.Files
import java.nio.file.Path
import java.security.MessageDigest
import java.util.HexFormat

require(args.size == 2) { "Usage: VerifyInitTail.main.kts STOCK_ELF GRAMMAR_TOML" }
val elfPath=Path.of(args[0]); val grammarPath=Path.of(args[1])
fun sha(bytes:ByteArray)=HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes))
fun sha(path:Path)=sha(Files.readAllBytes(path))
fun num(raw:String):Long { val s=raw.trim();require(s.matches(Regex("(?:0x[0-9a-fA-F]+|[0-9]+)"))){"bad integer $s"};return if(s.startsWith("0x"))s.drop(2).toLong(16) else s.toLong() }
fun bool(raw:String):Boolean=when(raw.trim()){ "true"->true;"false"->false;else->error("bad boolean $raw") }
fun str(raw:String):String { val s=raw.trim();require(s.length>=2&&s.first()=='"'&&s.last()=='"'){"bad string $s"};val out=StringBuilder();var i=1;while(i<s.lastIndex){val c=s[i++];if(c!='\\')out.append(c)else{require(i<s.lastIndex);when(val e=s[i++]){'\\'->out.append('\\');'"'->out.append('"');'n'->out.append('\n');'t'->out.append('\t');else->error("bad escape \\$e")}}};return out.toString() }
fun arr(raw:String):List<String>{val s=raw.trim();require(s.startsWith("[")&&s.endsWith("]")){"bad array $s"};val body=s.substring(1,s.lastIndex);if(body.isBlank())return emptyList();val out=mutableListOf<String>();var quoted=false;var escaped=false;var begin=0;for(i in body.indices){val c=body[i];if(escaped){escaped=false;continue};if(quoted&&c=='\\'){escaped=true;continue};if(c=='"')quoted=!quoted;if(c==','&&!quoted){out+=body.substring(begin,i).trim();begin=i+1}};require(!quoted&&!escaped);out+=body.substring(begin).trim();require(out.none(String::isEmpty));return out}
data class Tab(val kind:String,val line:Int,val array:Boolean,val v:LinkedHashMap<String,String> = linkedMapOf())
data class Doc(val root:LinkedHashMap<String,String>,val tabs:List<Tab>)
fun parse(path:Path):Doc { val root=linkedMapOf<String,String>();val tabs=mutableListOf<Tab>();var cur:Tab?=null
 Files.readAllLines(path).forEachIndexed{index,source->val line=source.trim();if(line.isEmpty()||line.startsWith("#"))return@forEachIndexed
  if(line.startsWith("[[")){require(line.endsWith("]]")){"bad array table line ${index+1}"};val k=line.substring(2,line.length-2).trim();require(k.matches(Regex("[a-z_][a-z0-9_]*")));cur=Tab(k,index+1,true);tabs+=cur!!;return@forEachIndexed}
  if(line.startsWith("[")){require(line.endsWith("]")&&!line.startsWith("[[")){"bad table line ${index+1}"};val k=line.substring(1,line.lastIndex).trim();require(k.matches(Regex("[a-z_][a-z0-9_]*")));require(tabs.none{it.kind==k&&!it.array}){"duplicate table $k"};cur=Tab(k,index+1,false);tabs+=cur!!;return@forEachIndexed}
  val eq=line.indexOf('=');require(eq>0){"bad assignment line ${index+1}"};val key=line.substring(0,eq).trim();require(key.matches(Regex("[a-z_][a-z0-9_]*")));val value=line.substring(eq+1).trim();require(value.isNotEmpty());val map=cur?.v?:root;require(map.put(key,value)==null){"duplicate $key line ${index+1}"}
 };return Doc(root,tabs)}

data class Seg(val file:Long,val virtual:Long,val size:Long)
data class Sec(val type:Int,val file:Long,val size:Long,val link:Int,val entry:Long)
data class Sym(val name:String,val value:Long,val size:Long,val section:Int)
data class Rel(val slot:Long,val type:Long,val symbol:Sym?)
class Elf(val raw:ByteArray){private val b=ByteBuffer.wrap(raw).order(ByteOrder.LITTLE_ENDIAN);private fun u16(p:Int)=b.getShort(p).toInt()and 0xffff;private fun u32(p:Int)=b.getInt(p).toLong()and 0xffffffffL;private fun u64(p:Int)=b.getLong(p);private val segs:List<Seg>;val symbols:Map<String,Sym>;val rels:Map<Long,Rel>
 init{require(raw.size>=64&&raw[0]==0x7f.toByte()&&String(raw,1,3)=="ELF"&&raw[4]==2.toByte()&&raw[5]==1.toByte()&&u16(18)==183){"not AArch64 ELF64 LE"};segs=(0 until u16(56)).map{u64(32).toInt()+it*u16(54)}.filter{u32(it)==1L}.map{Seg(u64(it+8),u64(it+16),u64(it+32))};val secs=(0 until u16(60)).map{u64(40).toInt()+it*u16(58)}.map{Sec(u32(it+4).toInt(),u64(it+24),u64(it+32),u32(it+40).toInt(),u64(it+56))};fun readSymbols(s:Sec):List<Sym>{require(s.entry==24L);val strings=secs[s.link];return (0 until(s.size/s.entry).toInt()).map{i->val p=(s.file+i*s.entry).toInt();val start=(strings.file+u32(p)).toInt();var end=start;while(raw[end]!=0.toByte())end++;Sym(String(raw,start,end-start),u64(p+8),u64(p+16),u16(p+6))}};val all=secs.filter{it.type==11}.flatMap(::readSymbols);symbols=all.filter{it.name.isNotEmpty()}.groupBy{it.name}.mapValues{(name,list)->val d=list.filter{it.section!=0};require(d.map{it.value to it.size}.distinct().size<=1){"conflicting $name"};d.firstOrNull()?:list.first()};val rm=mutableMapOf<Long,Rel>();secs.filter{it.type==4}.forEach{s->val linked=readSymbols(secs[s.link]);repeat((s.size/s.entry).toInt()){i->val p=(s.file+i*s.entry).toInt();val info=u64(p+8);val si=(info ushr 32).toInt();val r=Rel(u64(p),info and 0xffffffffL,if(si==0)null else linked[si]);require(rm.put(r.slot,r)==null){"duplicate ELF relocation"}}};rels=rm}
 private fun off(va:Long,n:Int):Int{val s=segs.filter{va>=it.virtual&&va+n<=it.virtual+it.size};require(s.size==1){"unmapped 0x${va.toString(16)}"};return(s.single().file+va-s.single().virtual).toInt()}
 fun bytes(va:Long,n:Int)=raw.copyOfRange(off(va,n),off(va,n)+n);fun word(va:Long)=ByteBuffer.wrap(bytes(va,4)).order(ByteOrder.LITTLE_ENDIAN).int.toLong()and 0xffffffffL}

val pinned="4e7eb0bb81b6bcc6923ceff75fd259d41be555dccc6867e53ed7ee2ea3b2894e"
val doc=parse(grammarPath);val elfBytes=Files.readAllBytes(elfPath);val elf=Elf(elfBytes)
require(sha(elfBytes)==pinned){"stock hash"}
val rootKeys=setOf("schema_version","stock_library_sha256","method","entry","parent_flow_complete","transitive_recovery_complete","candidate_boundary","exception_scope")
require(doc.root.keys==rootKeys){"root fields"};require(str(doc.root.getValue("schema_version"))=="mho900-lab.init-tail-grammar/1");require(str(doc.root.getValue("stock_library_sha256"))==pinned);require(str(doc.root.getValue("entry"))=="VERSION4");require(bool(doc.root.getValue("parent_flow_complete")));require(!bool(doc.root.getValue("transitive_recovery_complete")));require(str(doc.root.getValue("candidate_boundary"))=="CALIBRATION");require(str(doc.root.getValue("method")).contains("not a semantic proof"));require(str(doc.root.getValue("exception_scope")).isNotBlank())
val allowed=setOf("ranges","bindings","nodes","edges","accesses","clock_predicate","poll_projections");require(doc.tabs.all{it.kind in allowed});require(doc.tabs.count{it.kind=="clock_predicate"&&!it.array}==1);require(doc.tabs.filter{it.kind!="clock_predicate"}.all{it.array})

val requiredRanges=setOf("_Z8Drv_Initb","DevSystemSCU_GetVersion","DevSystemSCU_GetHardwareVersion","DevSystemScu_ReadRegister","DevAcquireSpu_ReadRegister","DevAcquireSpu_WriteRegister","DevAcquireSpu_SetDacPolling","DevConfig_GetDdrCalSkip","DevSystem_GetSeriesParam","DevAcquireSPU_GetDdrSkipTap","DevAcquireSPU_SetMemReset","DevAcquireSpu_SelfTest","DevAcquireSpu_GetCheckAdcClk","DevAcquireSpu_MemoryBram","_ZN12CCalibration4InitEv","_ZN11CApiFactory8Api_InitEv","_ZN11CApiUtility28ApiUtility_SetLowPowerStatusEi","DevAcquireSpu_SetAfeOffset","DevAcquireSpu_SetAdcBitRange","DevSystemSCU_SetLaEanble","DevSystemSCU_SetProcLaEn","DevSystemSCU_SetProcChEn")
val ranges=doc.tabs.filter{it.kind=="ranges"};val rangeNames=mutableSetOf<String>();for(t in ranges){require(t.v.keys==setOf("name","address","size","sha256")){"range fields line ${t.line}"};val name=str(t.v.getValue("name"));require(rangeNames.add(name));val sym=requireNotNull(elf.symbols[name]){"missing symbol $name"};val address=num(t.v.getValue("address"));val size=num(t.v.getValue("size"));require(sym.section!=0&&sym.value==address&&sym.size==size){"symbol range $name"};require(size in 1..1048576);require(sha(elf.bytes(address,size.toInt()))==str(t.v.getValue("sha256"))){"range hash $name"}}
require(rangeNames==requiredRanges){"range set"}

val requiredStateSlots=setOf(0xb8e118L,0xb8d288L,0xb8de08L,0xb8d850L,0xb8d640L,0xb8e050L,0xb8c9f0L,0xb8ba20L,0xb8be90L,0xb8d3a8L)
val exactBindingSlots=setOf(0xb785a8L,0xb78790L,0xb7bb08L,0xb7d7a8L,0xb7fb88L,0xb7ff00L,0xb833c0L,0xb83f18L,0xb84018L,0xb84548L,0xb845c0L,0xb85098L,0xb86148L,0xb86690L,0xb86758L,0xb86820L,0xb86f98L,0xb870a0L,0xb87630L,0xb883b8L,0xb89e08L,0xb8ba20L,0xb8be90L,0xb8c9f0L,0xb8d288L,0xb8d3a8L,0xb8d640L,0xb8d850L,0xb8de08L,0xb8e050L,0xb8e118L,0xbbc1c0L)
val bindings=doc.tabs.filter{it.kind=="bindings"};val slots=mutableSetOf<Long>();for(t in bindings){require(t.v.keys==setOf("slot","type","symbol","target")){"binding fields line ${t.line}"};val slot=num(t.v.getValue("slot"));require(slots.add(slot)){"duplicate binding slot"};val r=requireNotNull(elf.rels[slot]){"missing relocation 0x${slot.toString(16)}"};val symbol=str(t.v.getValue("symbol"));require(r.type==num(t.v.getValue("type"))&&r.symbol?.name==symbol&&r.symbol.value==num(t.v.getValue("target"))){"binding mismatch $symbol"}}
require(slots==exactBindingSlots){"binding slot set"};require(requiredStateSlots.all{it in slots}){"missing mutable-state binding"};require(requiredRanges.all{name->bindings.any{str(it.v.getValue("symbol"))==name}}){"missing function binding"}

val exactIds=setOf("VERSION4","VERSION0","VERSION_PACK","VERSION_HW","VERSION_LOG","DAC_TIME","DDR_SELECT","TAP0","TAP1","TAP2","TAP3","TAP4","TAP_OUTPUT","MEM_RESET","SELF_READ","SELF_PREDICATE","CLOCK_READ","CLOCK_PREDICATE","POLL_SELECT","POLL_DELAY","POLL_TEST","FALLBACK_SELECT","BRAM","CALIBRATION","ADC_MODE","ALIGN","AFE_OFFSET","SAMPLE_MASK","ADC_RANGE","CHANNEL_SCALE","SINC","FAN","SCOPE_START","AFE_ENABLE","LA_DISABLE","PROC_LA_DISABLE","PROC_CH_ENABLE","RETURN","STACK_FAILURE","UPSTREAM")
val hardware=setOf("VERSION4","VERSION0","VERSION_HW","TAP0","TAP1","TAP2","TAP3","TAP4","SELF_READ","CLOCK_READ","POLL_TEST")
val runtime=setOf("DDR_SELECT","POLL_SELECT","FALLBACK_SELECT","SAMPLE_MASK","ADC_RANGE","LA_DISABLE","PROC_LA_DISABLE","PROC_CH_ENABLE");val async=setOf("POLL_DELAY")
val unknown=setOf("CALIBRATION","ADC_MODE","ALIGN","CHANNEL_SCALE","SINC","FAN","SCOPE_START","AFE_ENABLE","STACK_FAILURE")
val nodes=doc.tabs.filter{it.kind=="nodes"};val nodeMap=linkedMapOf<String,Tab>();for(t in nodes){require(t.v.keys==setOf("id","classification","operation","semantics","pcs","opcodes","inputs")){"node fields"};val id=str(t.v.getValue("id"));require(nodeMap.put(id,t)==null){"duplicate node $id"};val expected=when(id){in hardware->"HARDWARE-RETURNED";in runtime->"RUNTIME-SELECTED";in async->"ASYNCHRONOUS";in unknown->"UNKNOWN";else->"STATIC-DETERMINED"};require(str(t.v.getValue("classification"))==expected){"classification $id"};require(str(t.v.getValue("operation")).isNotBlank()&&str(t.v.getValue("semantics")).isNotBlank());val pcs=arr(t.v.getValue("pcs")).map(::num);val ops=arr(t.v.getValue("opcodes")).map(::num);require(pcs.isNotEmpty()&&pcs.size==ops.size){"pc/opcode $id"};pcs.zip(ops).forEach{(pc,op)->require(elf.word(pc)==op){"opcode $id 0x${pc.toString(16)}"}};arr(t.v.getValue("inputs")).forEach(::str)}
require(nodeMap.keys==exactIds){"node set"};require(str(nodeMap.getValue("CALIBRATION").v.getValue("classification"))=="UNKNOWN");require(str(nodeMap.getValue("SCOPE_START").v.getValue("classification"))=="UNKNOWN")

data class Edge(val from:String,val to:String)
val edges=doc.tabs.filter{it.kind=="edges"}.map{t->require(t.v.keys==setOf("from","to","condition"));require(str(t.v.getValue("condition")).isNotBlank());Edge(str(t.v.getValue("from")),str(t.v.getValue("to")))}
val chain=listOf("VERSION4","VERSION0","VERSION_PACK","VERSION_HW","VERSION_LOG","DAC_TIME","DDR_SELECT").zipWithNext().map{Edge(it.first,it.second)}+listOf("TAP0","TAP1","TAP2","TAP3","TAP4","TAP_OUTPUT","MEM_RESET","SELF_READ","SELF_PREDICATE","CLOCK_READ","CLOCK_PREDICATE","POLL_SELECT").zipWithNext().map{Edge(it.first,it.second)}+listOf("BRAM","CALIBRATION","ADC_MODE","ALIGN","AFE_OFFSET","SAMPLE_MASK","ADC_RANGE","CHANNEL_SCALE","SINC","FAN","SCOPE_START","AFE_ENABLE","LA_DISABLE","PROC_LA_DISABLE","PROC_CH_ENABLE").zipWithNext().map{Edge(it.first,it.second)}
val branches=setOf(Edge("DDR_SELECT","TAP0"),Edge("DDR_SELECT","SELF_READ"),Edge("POLL_SELECT","CALIBRATION"),Edge("POLL_SELECT","POLL_DELAY"),Edge("POLL_DELAY","POLL_TEST"),Edge("POLL_TEST","POLL_SELECT"),Edge("POLL_SELECT","FALLBACK_SELECT"),Edge("FALLBACK_SELECT","BRAM"),Edge("FALLBACK_SELECT","CALIBRATION"),Edge("PROC_CH_ENABLE","RETURN"),Edge("PROC_CH_ENABLE","STACK_FAILURE"),Edge("RETURN","UPSTREAM"))
require(edges.toSet()==(chain.toSet()+branches)&&edges.size==edges.toSet().size){"flattened/missing/extra edge"}
val reached=mutableSetOf("VERSION4");while(true){val n=reached.size;edges.filter{it.from in reached}.forEach{reached+=it.to};if(n==reached.size)break};require(reached==exactIds){"unreachable nodes"}

data class AccessContract(val node:String,val dir:String,val offset:Long,val pc:Long,val opcode:Long)
val accessContract=linkedMapOf(
 "version4" to AccessContract("VERSION4","READ",4,0x285300,0x97fe2ab4),"version0" to AccessContract("VERSION0","READ",0,0x285310,0x97fe2ab0),"hardware_version" to AccessContract("VERSION_HW","READ",0x401c,0x285394,0x97fe2a8f),"dac_time" to AccessContract("DAC_TIME","WRITE",0x1428,0x27dd88,0x97fe587a),"tap0" to AccessContract("TAP0","READ",0x14a0,0x27d4cc,0x97fe693d),"tap1" to AccessContract("TAP1","READ",0x14a4,0x27d5a0,0x97fe6908),"tap2" to AccessContract("TAP2","READ",0x1498,0x27d678,0x97fe68d2),"tap3" to AccessContract("TAP3","READ",0x14ac,0x27d750,0x97fe689c),"tap4" to AccessContract("TAP4","READ",0x14b4,0x27d828,0x97fe6866),"mem_reset" to AccessContract("MEM_RESET","WRITE",0x1000,0x277d8c,0x97fe7079),"self_status" to AccessContract("SELF_READ","READ",0x1008,0x2735c0,0x97fe9100),"self_clock" to AccessContract("CLOCK_READ","READ",0x1210,0x2734c8,0x97fe913e),"bram" to AccessContract("BRAM","WRITE",0x1008,0x2739a8,0x97fe8172),
 "afe0" to AccessContract("AFE_OFFSET","WRITE",0x1418,0x27ddfc,0x97fe585d),"afe1" to AccessContract("AFE_OFFSET","WRITE",0x141c,0x27de10,0x97fe5858),"afe2" to AccessContract("AFE_OFFSET","WRITE",0x1420,0x27de24,0x97fe5853),"afe3" to AccessContract("AFE_OFFSET","WRITE",0x1424,0x27de38,0x97fe584e),"adc_range" to AccessContract("ADC_RANGE","WRITE",0x1014,0x273340,0x97fe830c),"la_disable" to AccessContract("LA_DISABLE","WRITE",0x4008,0x286828,0x97fe219e),"proc_la_disable" to AccessContract("PROC_LA_DISABLE","WRITE",0x4008,0x2865a0,0x97fe2240),"proc_ch_enable" to AccessContract("PROC_CH_ENABLE","WRITE",0x4008,0x28660c,0x97fe2225))
val accesses=doc.tabs.filter{it.kind=="accesses"};val seenAccess=mutableSetOf<String>();for(t in accesses){require(t.v.keys==setOf("id","node","direction","offset","width","expression","condition","call_pc","call_opcode")){"access fields"};val id=str(t.v.getValue("id"));require(seenAccess.add(id));val e=requireNotNull(accessContract[id]){"extra access $id"};require(str(t.v.getValue("node"))==e.node&&str(t.v.getValue("direction"))==e.dir&&num(t.v.getValue("offset"))==e.offset&&num(t.v.getValue("width"))==4L&&num(t.v.getValue("call_pc"))==e.pc&&num(t.v.getValue("call_opcode"))==e.opcode&&elf.word(e.pc)==e.opcode){"access $id"};require(str(t.v.getValue("expression")).isNotBlank()&&str(t.v.getValue("condition")).isNotBlank());if(id in setOf("afe0","afe1","afe2","afe3","adc_range","la_disable"))require(str(t.v.getValue("condition")).contains("return")){"post-calibration condition $id"}}
require(seenAccess==accessContract.keys){"missing access, including R1210"}

val clock=doc.tabs.single{it.kind=="clock_predicate"};require(clock.v.keys==setOf("nominal_bits","tolerance_bits","strict","first_accepted_u32","last_accepted_u32","controls_parent_retry"));require(num(clock.v.getValue("nominal_bits"))==0x47742400L&&num(clock.v.getValue("tolerance_bits"))==0x38d1b717L&&bool(clock.v.getValue("strict"))&&!bool(clock.v.getValue("controls_parent_retry")));val nominal=Float.fromBits(0x47742400);val tolerance=Float.fromBits(0x38d1b717);val low=nominal*(1f-tolerance);val high=nominal*(1f+tolerance);val accepted=(62480L..62520L).filter{it.toFloat()>low&&it.toFloat()<high};require(accepted.first()==num(clock.v.getValue("first_accepted_u32"))&&accepted.last()==num(clock.v.getValue("last_accepted_u32"))&&accepted==(62494L..62506L).toList()){"clock range"}

data class Projection(val ready:Long,val pairs:Long,val sleeps:Long,val fallback:Boolean)
val projectionContract=mapOf("first_ready" to Projection(1,1,0,false),"second_ready" to Projection(2,2,1,false),"last_ready" to Projection(201,201,200,false),"never_ready" to Projection(0,201,200,true));val projections=doc.tabs.filter{it.kind=="poll_projections"};val projectionNames=mutableSetOf<String>();for(t in projections){require(t.v.keys==setOf("name","ready_at","read_pairs","sleep_requests","fallback_write","observed"));val name=str(t.v.getValue("name"));require(projectionNames.add(name));val e=requireNotNull(projectionContract[name]);require(num(t.v.getValue("ready_at"))==e.ready&&num(t.v.getValue("read_pairs"))==e.pairs&&num(t.v.getValue("sleep_requests"))==e.sleeps&&bool(t.v.getValue("fallback_write"))==e.fallback&&!bool(t.v.getValue("observed"))){"projection $name"}}
require(projectionNames==projectionContract.keys){"poll projections"}

println("schema_version = \"mho900-lab.init-tail-verification/1\"")
println("result = \"accepted\"")
println("stock_library_sha256 = \"$pinned\"")
println("grammar_sha256 = \"${sha(grammarPath)}\"")
println("ranges = ${ranges.size}\nbindings = ${bindings.size}\nnodes = ${nodes.size}\nedges = ${edges.size}\naccesses = ${accesses.size}\npoll_projections = ${projections.size}")
println("structural_limit = \"ELF identity, symbols, relocations, bytes, graph shape, access ABI, clock arithmetic, and bounded projections verified\"")
println("semantic_limit = \"Manual node semantics text and UNKNOWN callee behavior are not proven by this verifier\"")
